### ISSUE TITLE
Unable to find DashApp and GNDecoratorT in DashboardV2

### ISSUE THREAD

**Issue by nextdevlpr** [gleidsonmt/DashboardFx#27]
Hi @Gleidson28,

As I am curious to see new features and controls added in DashboardV2, but unable to open it properly.

**Comment by Gleidson28** [comment]
Hi, in this moment, I am stopped most projects.. but if you switch the branch..

**Comment by FxamarAboali** [comment]
can get the new DashboardV2 please

**Comment by FxamarAboali** [comment]
can get the new DashboardV2 please

**Comment by gleidsonmt** [comment]
I'm sorry, this is a test branch.. I trying to launch one solid version..

Em ter., 22 de nov. de 2022 17:08, FxamarAboali ***@***.***>
escreveu:

**Comment by FxamarAboali** [comment]
Hi @Gleidson28,

Sorry
I did not understand what you mean, do you want me to buy the program from you?


I want an integrated program that helps me solve all my problems with the Java interfaces, which have become complicated because of the interfaces in other languages, but I am proficient in Javafx and I do not have the design skill, but I am good at dealing with the language

**Comment by gleidsonmt** [comment]
Oh, I understand.. at this time javafx.. isn't good start fast.. I made one new version that contains more maintanable components.. i'm studying how to work a big ecosystem like a dashboard.. i was miss.. but i return in full
