### ISSUE TITLE
Previous Version of Dashboard.fx

### ISSUE THREAD

**Issue by asifalieloq** [gleidsonmt/DashboardFx#46]
I ran previously shared simple javafx project but currently missing some libraries to run that project again. Also it looks like that project has been removed from gihub.

I will be thank full on providing any guidance related to this.

Thank you

**Comment by gleidsonmt** [comment]
@asifalieloq Hi, I understand that you're facing difficulties with outdated or unsupported JavaFX 8 projects and now I trying to work on my own with the library. You mentioned that using Gradle is more convenient for you, but it's also possible to build JavaFX +11 projects without Gradle by downloading the dependencies from OpenJFX.

To assist you further, I would need more specific information about the missing libraries in your project. If you could provide me with the error messages or the specific functionality you're trying to implement, I can help identify which libraries might be missing and guide you on how to obtain them. Additionally, please let me know your specific goals or requirements so that I can provide more targeted assistance.

Please provide the necessary details, and I'll do my best to help you.
